# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '27th_iOS_4Week_Seminar_Project' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 27th_iOS_4Week_Seminar_Project
  
pod 'FSCalendar'

end
